# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=100)),
                ('twitch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vidcue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Ytvideo')),
            ],
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Player'),
        ),
    ]
