# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170205_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='trimmed_path',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='vid_path',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
