# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_player_twitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
