# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
