# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_ytvideo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='vid_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
