# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_ytvideo_vid_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='hero',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
