# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20170207_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidcue',
            name='end',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='vidcue',
            name='start',
            field=models.CharField(max_length=2),
        ),
    ]
