# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20170207_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidcue',
            name='end',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vidcue',
            name='start',
            field=models.CharField(max_length=10),
        ),
    ]
